### ISSUE TITLE
Shorten hangs in FF when shortening hidden items

### ISSUE THREAD

**Issue by generalredneck** [MarcDiethelm/jQuery-Shorten#2]
To be more precise, it will stop responding when you have a scenario where the item to be shortened is the child of an item that is a child of something that is hidden. Consider the following:
EDIT: putting code in a file because I'm having a hard time getting it to show in here.
http://dl.dropbox.com/u/7177934/shorten_bugs/code.html

This is an example where firefox will hang and you get the following
http://dl.dropbox.com/u/7177934/shorten_bugs/screenshot_170.png

If there is anything else you need me to provide I can. I've been able to reproduce this on several versions of FF in linux, mac, and windows. Chrome and IE6 seem to be ok.

**Comment by MarcDiethelm** [comment]
Confirmed for jQuery < 1.4.4.

This issue is the result of jQuery not being able to return a meaningful value when using .width() on an element that has display:none. This method is used initially to get the target width from the parent block (if none is supplied).  In your testcase the returned values were negative, leading to an infinite loop.

http://bugs.jquery.com/ticket/7225

Workarounds:
- Use jQuery 1.4.4+  
- Supply a target width in options.  
- Use better timing: Don't use display:none when shortening (maybe you can use visibility:hidden). Or shorten after changing display.

The code has been fixed so no infinite loop occurs. I won't however backport a jQuery bugfix into the plugin... this is a jQuery issue. So for elements that have display:none and don't have a target width set in options the plugin will simply do nothing.

Thanks for reporting this!

**Comment by MarcDiethelm** [comment]
By the way: Your usage of white-space:nowrap; defeats the native text-overflow:ellipsis in browsers that support it (like Safari), no ellipsis appears in this case.
